### ISSUE TITLE
prefmanager fails to install with sandbox mode enabled

### ISSUE THREAD

**Issue by astratagem** [malob/prefmanager#2]
Hi @malob – thanks for your excellent work on https://github.com/malob/nixpkgs – I've borrowed some ideas and snippets in my own config. That's how I came across `prefmanager`.

However, I haven't been able to install `prefmanager` on my Intel MBP via `environment.systemPackages` or as a user package with `nix.useSandbox` set to `true` (the default on NixOS, FWIW). After I rebuild with `nix.useSandbox = false;` I'm able to install `prefmanager` successfully.

This looks like an instance of https://github.com/NixOS/nix/issues/4119 – though I'm not sure what to suggest. Aside from `prefmanager`, I haven't run into any issues with sandbox mode, which I've had enabled for a while now.

Each time I build my flake-based system configuration I receive the following error:

```
building '/nix/store/yg5d4940nq5xqnnrn7nvlmid440p265k-darwin-system-21.11.20211220.df6791e+darwin4.a2ed0b0.drv'...
error: builder for '/nix/store/yg5d4940nq5xqnnrn7nvlmid440p265k-darwin-system-21.11.20211220.df6791e+darwin4.a2ed0b0.drv' failed with exit code 65;
       last 1 log lines:
       > sandbox-exec: pattern serialization length 66284 exceeds maximum (65535)
       For full logs, run 'nix log /nix/store/yg5d4940nq5xqnnrn7nvlmid440p265k-darwin-system-21.11.20211220.df6791e+darwin4.a2ed0b0.drv'.
```

Unfortunately, there's nothing else in the log.

**Comment by malob** [comment]
Thanks for the heads up. I’ll try and find some time to tinker with sandboxing and see if I can figure out what the issue is.

**Comment by malob** [comment]
Sorry for taking so long to come around to looking into this.

I just ran `nix build --option sandbox true` and didn't have any build issues.

Maybe something got resolved upstream with Nix?
